### ISSUE TITLE
iki tane sorucuk

### ISSUE THREAD

**Issue by MSKose** [marcus-clarusway/Git-Lessons#10]

**Comment by MSKose** [comment]
iki gun once iki tane issue acmistim, cevap gelmeyince bir sikinti oldugunu anladim. meger 3. session’a yaziyormusum. iki soruyu direkt buraya da kopyaliyorum:

1. Hocam bugun farkina vardim ki ben iki sene once bir github hesabi acmisim. tabii hic kullanmadigim icin icinde hic girdi yok. sizce yeni hesabi mi kullanayim yoksa eskinin uzerinden mi devam edeyim?
2. hocam derste bir yerde index dosyasinin icine '''bash ''' eklemistiniz. bu ne ise yariyor??

**Comment by Musti4096** [comment]
Merhaba @MSKose,
1. onceden actigin GitHub hesabini kullanabilirsin.
2. orada ekledegim bash ifadesi MarkDown formatindan Linux terminal kodlarinin guzel sekilde sergilenmesini sagliyor. Bu hafta onu isleyyecegiz. Ornek olarak asagiya bir kod birakayim.

```bash
sudo apt update -y && sudo apt upgrade -y
echo "Hello World" >> text.txt
```
