### ISSUE TITLE
Branch Problem 

### ISSUE THREAD

**Issue by Habip2542** [marcus-clarusway/Git-Lessons#12]
Git workshop ödevinde yapılan adımları sırası ile;
- Master brach da test isimli dosyayı oluşturuyorum.
- Daha sonra new feature isimli yeni branch oluşturuyorum.
- New feature branch ına geçtikten sonra test isimli dosyada değişiklik yapıyorum.
- Daha sonra master branchına geçtiğim zaman test dosyası master branchında görünmüyor.
- Hem new feature branchında commit etmeden önce denedim hem de commit ettikten sonra denedim.
  master branchına geçince sadece README dosyası   görünüyor. 
  Bişeleri eksik veya hatalı yapıyorum, yardımxı olabilecek var mı acaba.  History aşağıdaki şekildedir 
  
 506  git clone https://github.com/Habip2542/git-workshop-2.git
  507  cd git-workshop-2/
  508  ls -al
  509  touch test.txt
  510  git branch new-feature-1
  511  git branch
  512  git checkout new-feature-1
  513  ls -al
  514  git status
  515  vim test.txt
  516  git status
  517  git add .
  518  git commit -m "added first line"
  519  git status
  520  git checkout master
  521  ls

**Comment by Musti4096** [comment]
master branch uzerine dosya olusturduktan sonra commit etmemissin. Daha sonra diger branche gecip islemlerini orada yaptigin icin, master branch'e geri dondugunde keydedilmeyen dosyalari bulamaman normal. Hata yapmiyorsun,

**Comment by Habip2542** [comment]
hocam o zaman anladığım kadarıyla test dosyasını oluşturduktan sonra önce master branch ında commit edeceğim daha sonra new feature branch ine geçeceğim orada değişiklikleri yaptıktan sonra orada da commit edip daha sonra tekrar master a geçip diğer işlemlere devam edeceğim. Doğru mu anlamışım acaba ?
