### ISSUE TITLE
Branch silme problemi

### ISSUE THREAD

**Issue by MeryemTtk** [marcus-clarusway/Git-Lessons#13]
Hocam dünkü workshopta olusturdugumuz branch(new-feature-2) i master la birlestirdikten sonra silemedim.Sebebi branch leri birlestirdikten sonra artik öyle bir branchin olmamasi mi?

**Comment by adonmez04** [comment]
silmek icin hangi komutlari kullandiniz hocam?

**Comment by kemalayana** [comment]
muhtemelen

**Comment by MeryemTtk** [comment]
> silmek icin hangi komutlari kullandiniz hocam?

git branch -D new-feature-2  
komutunu kullanmistim,ilk olusturdugum new-feature-1 silindi ayni konutla ama muhtemelen bir hata yaptim ikincisinde.
