### ISSUE TITLE
git commit -am komutu çalışmıyor

### ISSUE THREAD

**Issue by erhankorkut16** [marcus-clarusway/Git-Lessons#15]
![image](https://user-images.githubusercontent.com/101005277/159871971-3674604d-3983-4c24-b80d-8287631ac833.png)

ekteki hatayı alıyorum ne yapabilirim

**Comment by Fthhbsr** [comment]
Hocam stage e almadan commit yapmışsınız galiba.
git add .   yapıp tekrar commit etmeyi denermisiniz

**Comment by Musti4096** [comment]
yeni olusturulan dosyalar icin -am secenegi calismiyor, once add ile stage'e cekmek lazim.

**Comment by firatolcum** [comment]
Hocam hatadan anladığım şu: working area'da den.txt isimli bir metin belgeniz var ancak bu belge staging area'ya çekilmemiş. git add den.txt komutu ile belgeyi staging area'ya çekip git commit -m "commit için mesaj" komutu ile commit edebilirsiniz. En son git push ile de github'daki repository' gönderebilirsiniz.

**Comment by erhankorkut16** [comment]
ilk oluşturduğumuz dosyaları da direkt "commit -am" komutu ile commit edebiliyoruz sanmıştım. yardımınız için teşekkürler
