### ISSUE TITLE
Branch Problemi

### ISSUE THREAD

**Issue by Federaltr** [marcus-clarusway/Git-Lessons#16]
Master branch'inde  test.txt dosyası oluşturdum.
Bu dosyayı git add ve git commit komutlarıyla commit ettim.
Sonra new-feature-1 branch'ine geçtim.
Burda dosyaları listelediğimde sadece readme dosyasını görüyorum. test.txt dosyası bu branchde görünmüyor.
Burda aynı isimli dosyayı kendim mi oluşturmalıyım yoksa bu branch de görmem mi gerekiyor?

**Comment by firatolcum** [comment]
Hocam workshop için gönderilen dökümanın son maddelerinde hatalar var. new-feature-2 branch' i olması lazım .Eğer bu bahsettiğiniz workshop ile ilgili ise.

**Comment by firatolcum** [comment]
Hangi aşamaya denk geliyor porbleminiz ?

**Comment by yaserdemet** [comment]
yeni bir branch actıysanız masterdan dosyalarınızın gelmesi gerekir. gelmiyorsa yeni branch te iken  merge yapmanız daha uygun olur. Eğer github tan clone yaptıysanız , calısmaya baslamadan git pull yapmanızda her zaman fayda var.
