### ISSUE TITLE
git push problem

### ISSUE THREAD

**Issue by arslantobe** [marcus-clarusway/Git-Lessons#9]
![image](https://user-images.githubusercontent.com/101005130/159470124-00ae6c86-fd9a-4ba0-8d4f-73eb2029201c.png)

bu hatayı alıyorum sebebi ne olabilir?

**Comment by MSKose** [comment]
git remote -v

git init the repo URL

git remote add origin the repo URL

git push -f origin master

**Comment by avcimehmet** [comment]
Bende de benzer bir problem vardı.

**git pull --rebase origin master**

yapınca düzeldi.

**Comment by arslantobe** [comment]
> Bende de benzer bir problem vardı.
> 
> **git pull --rebase origin master**
> 
> yapınca düzeldi.

**Comment by arslantobe** [comment]
Teşekkür ederim yardımlarınız için.
